from utility.enums  import FpFormatE, IntFormatE


CYCLE_TIME  = 20 * 1e-9 #ns
HZ          = (1 / CYCLE_TIME) # 50Mhz while time_cycle = 20ns

CORES_CNT   = 1 # CORES COUNT IN THIS CONFIGURATION
THREADS_CNT = 4 # THREADS COUNT IN THIS CONFIGURATION PER CORE

DEFAULT_F_T = FpFormatE.FP64
DEFAULT_I_T = IntFormatE.INT64


DW          = 32 # DATA WIDTH
AW          = 5  # ADDR WIDTH
OP_W        = 5  # OPERATION WIDTH (WITH NO TYPE OP)
OP_T_W      = 2  # OPERATION TYPE WIDTH

VID_ADDR    = 31 # REGISTER ADDRESS WITH VERTEX ID
ZERO_ADDR   = 0  # REGISTER ADDRESS WITH ZERO CONSTANT VALUE

BYTES_CNT   = int(DW / 8)